type: object
title: EvaluationJobConfigCommon1
description: >
  The evaluation job request configuration.
required:
  - name
properties:
  name:
    type: string
    description: >
      The evaluation job name.
  description:
    type: string
    description: >
      The evaluation job description.
  tags:
    type: array
    items:
      type: string
    description: >
      The evaluation job tags.
  model:
    $ref: ./ModelRef.yaml
    description: |
      The model to evaluate.

      **Note that if `pre_recorded_data` is set for all `test_data_ref.type` in the `benchmarks` section then `model` will not be `required` for the job run, in all other cases a `model` is required.**
